version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    image: flask-react_client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: flask-react_server
    ports:
      - "5000:5000"
    links:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
